{
 "title": "Delegate Agent Resource calls",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values({__name__=\"active_delegate_count\"},environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=\"active_delegate_count\"},cluster)"
    }
   },
   { "name": "status", "label": "Status", "query": "1xx , 2xx , 3xx , 4xx , 5xx" }
  ]
 },
 "panels": [
  {
   "title": "rate_by_status_code (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{resource=\"DelegateAgentResource\", cluster=\"$cluster\", environment=\"$env\", statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{resource=\"DelegateAgentResource\", cluster=\"$cluster\", environment=\"$env\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "api_calls_sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) \n(rate(software_wings_resources_responses_count{resource=\"DelegateAgentResource\", cluster=\"$cluster\", environment=\"$env\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by (method) (software_wings_resources_responses_latency_snapshot_95thPercentile{resource=\"DelegateAgentResource\", cluster=\"$cluster\", environment=\"$env\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 more than 5 sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by (method) (software_wings_resources_responses_latency_snapshot_95thPercentile{resource=\"DelegateAgentResource\", cluster=\"$cluster\", environment=\"$env\"} > 5)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}