{
 "title": "Generic Infra Monitoring Dashboard",
 "description": "Dashboard for Monitoring daily health of the services",
 "tags": [
  "PL",
  "CAE",
  "Platform",
  "weekly-monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "container",
    "label": "Container",
    "query": "access-control , platform-service , manager-iterator , manager , ng-manager , gateway , ng-dashboard-aggregator , audit-event-streaming , chatbot-service , redis-streams-monitor , ng-auth-ui , genai-service , agent-gateway"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "kubernetes_io:container_uptime{container_name=~\"platform-service.*\"}"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", container=~\"$container\"}, namespace)\n"
    }
   },
   {
    "name": "pod",
    "label": "Pods",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\" , container=\"$container\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$container Memory Util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kubernetes_io:container_memory_used_bytes{cluster_name=~\"$cluster\", namespace_name=~\"$namespace\", container_name=~\"$container.*\", pod_name=~\"$pod\"}) by(namespace_name, pod_name, container_name) ",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum(kubernetes_io:container_memory_limit_bytes{cluster_name=~\"$cluster\", namespace_name=~\"$namespace\", container_name=~\"$container.*\", pod_name=~\"$pod\"}) by (namespace_name, pod_name, container_name)",
     "legendFormat": "Limit/{{pod_name}}"
    }
   ]
  },
  {
   "title": "$container CPU util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kubernetes_io:container_cpu_request_cores{namespace_name=~\"$namespace\", container_name=~\"$container.*\" , pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "rate(kubernetes_io:container_cpu_core_usage_time{namespace_name=~\"$namespace\", container_name=~\"$container\" , pod_name=~\"$pod\"}[$__interval])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(namespace_name, container_name) (round(rate(kubernetes_io:container_uptime{cluster_name=~\"$cluster\", namespace_name=~\"$namespace\", container_name=~\"$container.*\", pod_name=~\"$pod\"}[5m]), 0.001))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(namespace_name, container_name) (delta(kubernetes_io:container_restart_count{cluster_name=~\"$cluster\", namespace_name=~\"$namespace\", container_name=~\"$container.*\", pod_name=~\"$pod\"}[2m]) / 2)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "$container last 1 hr error ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time(logging_googleapis_com:log_entry_count{monitored_resource=\"k8s_container\", severity=~\"ERROR\", cluster_name=~\"$cluster\", namespace_name=~\"$namespace\", container_name=~\"$container\"}[1h])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Image version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum by (namespace, container, image_spec, version) (label_replace(kube_pod_container_info{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\"}, \"version\", \"$1\", \"image_spec\", \".*/([0-9a-z-]+[:@].*)\")) * 0 + 1",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}