{
 "title": "Outbox Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=\"outbox_queue_size\"}, cluster)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=\"outbox_queue_size\"}, environment)"
    }
   },
   {
    "name": "serviceId",
    "label": "serviceId",
    "query": {
     "query": "label_values({__name__=\"outbox_queue_size\"}, serviceId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "total_outbox_entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(serviceId) (outbox_queue_size{cluster=\"$cluster\", environment=\"$environment\", serviceId=\"$serviceId\", eventType=\"AllEventTypes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total_blocked_outbox_entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(serviceId) (outbox_blocked_queue_size{cluster=\"$cluster\", environment=\"$environment\", serviceId=\"$serviceId\", eventType=\"AllEventTypes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total_outbox_entries_by_event_type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(eventType) (outbox_queue_size{cluster=\"$cluster\", environment=\"$environment\", serviceId=\"$serviceId\", eventType!=\"AllEventTypes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total_blocked_outbox_entries_by_event_type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(eventType) (outbox_blocked_queue_size{cluster=\"$cluster\", environment=\"$environment\", serviceId=\"$serviceId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outbox_entries_processing_time_by_resource_type (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(resourceType) (rate(outbox_event_processing_time_sum{cluster=\"$cluster\", environment=\"$environment\", serviceId=\"$serviceId\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outbox_entries_delay_by_resource_type (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by(resourceType) (rate(outbox_event_waiting_time_sum{cluster=\"$cluster\", environment=\"$environment\", serviceId=\"$serviceId\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outbox_entries_processing_time_by_event_type (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by(eventType) (rate(outbox_event_processing_time_sum{cluster=\"$cluster\", environment=\"$environment\", serviceId=\"$serviceId\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outbox_entries_delay_by_event_type (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg by(eventType) (rate(outbox_event_waiting_time_sum{cluster=\"$cluster\", environment=\"$environment\", serviceId=\"$serviceId\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}