{
 "title": "Perpetual Tasks",
 "tags": [ "0compatible" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values({__name__=\"perpetual_tasks_num\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=\"perpetual_tasks_num\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pepetual_tasks_number",
   "type": "timeseries",
   "description": "number of perpetual tasks",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max by(accountId) (perpetual_tasks_num{cluster=\"$cluster\", environment=\"$env\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "perpetual_tasks_assigned_num",
   "type": "timeseries",
   "description": "number of perpetual tasks",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(max by(accountId) (perpetual_tasks_assigned_num{cluster=\"$cluster\", environment=\"$env\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "perpetual_tasks_unassigned_num",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(max by(accountId) (perpetual_tasks_unassigned_num{cluster=\"$cluster\", environment=\"$env\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "perpetual_invalid_tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(max by(accountId) (perpetual_invalid_tasks{cluster=\"$cluster\", environment=\"$env\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "perpetual_tasks_non_assignable_num",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(max by(accountId) (perpetual_tasks_non_assignable_num{cluster=\"$cluster\", environment=\"$env\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "perpetual_task_assign_delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by() (delta(iterator_delay_sum{cluster=\"$cluster\", environment=\"$env\", iteratorName=\"PerpetualTaskAssignment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "perpetual_tasks_created",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(delta(perpetual_task_create_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "perpetual_tasks_assigned",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(delta(perpetual_task_assigned_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "perpetual_tasks_paused_num",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(max by(accountId) (perpetual_tasks_paused_num{cluster=\"$cluster\", environment=\"$env\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}