{
 "title": "SRM SLI Dashboard",
 "tags": [ "SRM" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(io_harness_cvng_resources_request_filtering_count, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prod1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLO Create 5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{namespace=\"harness-nextgen\", method=\"saveSLOV2Data\", resource=\"ServiceLevelObjectiveV2Resource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO Create API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"saveSLOV2Data\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO Update 5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"updateSLOV2Data\", resource=\"ServiceLevelObjectiveV2Resource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO Update API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"updateSLOV2Data\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO Get 5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"getServiceLevelObjectivesV2\", resource=\"ServiceLevelObjectiveV2Resource\", statusCode=\"5xx\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO get API latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"getServiceLevelObjectiveV2\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Save monitored service  5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"saveMonitoredService\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Save MS API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"saveMonitoredService\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Monitored Service 5xx [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"updateMonitoredService\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update MS API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"updateMonitoredService\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitored service List 5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"getListV2\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MS List API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen\", method=\"getListV2\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prod2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO Create 5xx[5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"saveSLOV2Data\", resource=\"ServiceLevelObjectiveV2Resource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Create API Request latency [95th percentile] ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"saveSLOV2Data\", quantile=\"0.95\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Update 5xx[5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"updateSLOV2Data\", resource=\"ServiceLevelObjectiveV2Resource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Update API Request latency [95th percentile] ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"updateSLOV2Data\", quantile=\"0.95\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO List 5xx[5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{statusCode=\"5xx\", cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"getServiceLevelObjectivesV2\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO List API latency [95th percentile] ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"getServiceLevelObjectivesV2\", quantile=\"0.95\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Save monitored service  5xx[5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"saveMonitoredService\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Save MS API Request latency [95th percentile] ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"saveMonitoredService\", quantile=\"0.95\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update Monitored Service 5xx [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"updateMonitoredService\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update MS API Request latency [95th percentile] ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"updateMonitoredService\", quantile=\"0.95\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Monitored service List 5xx[5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"getListV2\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MS List API Request latency [95th percentile] ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-free\", method=\"getListV2\", quantile=\"0.95\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "prod3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "SLO Create 5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"saveSLOV2Data\", resource=\"ServiceLevelObjectiveV2Resource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO Create API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"saveSLOV2Data\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO Update 5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"updateSLOV2Data\", resource=\"ServiceLevelObjectiveV2Resource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO Update API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"updateSLOV2Data\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO List 5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{statusCode=\"5xx\", cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"getServiceLevelObjectivesV2\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO List API latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"getServiceLevelObjectivesV2\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Save monitored service  5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=~\"saveMonitoredService\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Save MS API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"saveMonitoredService\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Monitored Service 5xx [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"updateMonitoredService\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update MS API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"updateMonitoredService\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitored service List 5xx[5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"getListV2\", resource=\"MonitoredServiceResource\", statusCode=\"5xx\"}[5m])) / sum by(method) (rate(io_harness_cvng_resources_responses_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MS List API Request latency [95th percentile] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "max by(method) (io_harness_cvng_resources_total{cluster=\"$cluster\", namespace=\"harness-nextgen-compliance\", method=\"getListV2\", quantile=\"0.95\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}