{
 "title": "FF Customer Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AccountID",
    "label": "Account ID",
    "query": "All : .*, Simpplr : nh1pCWJXSReBDf3Ibh0kQg, SCB : _-ITnAA2Sg6fPowwXWzlxg ,  cust2 ===X4qbpncMSyKP3yDfAEqHzw, ZeroFlucs : rvvu5i6TQ3yTomFmk_NR0g, 26TRmCAhRRKVB3UUD_q11g : 26TRmCAhRRKVB3UUD_q11g, 0imfjG07TR2hVBcS5AZpCQ : 0imfjG07TR2hVBcS5AZpCQ, Yum Brands : LBcoZcDQQUS37ccH4lViQQ, The Real Real : bzykiJh8S0SHReAeHJr4QQ, Harness-FF-Prod1 : \nk4e8Jrt5THWe0Owle0Gr-Q, Harness-FF-Prod2 : \n31bhHXSHSRKo9Ud8U4-1VQ, Harness-FF-Prod3 : \nWki8Hz1eRRqJJvLlJAYZOw, Goldcast : F6yB5uRTQ5Cod6MWQoQXdg,BigThree:nh1pCWJXSReBDf3Ibh0kQg|-ITnAA2Sg6fPowwXWzlxg|bzykiJh8S0SHReAeHJr4QQ, QbXF1VIZTIC2-ueN1uTWHQ : QbXF1VIZTIC2-ueN1uTWHQ, Tessian : NtP2d9KbQGmdlL8LEkN-rA, X4qbpncMSyKP3yDfAEqHzw : X4qbpncMSyKP3yDfAEqHzw, Spotana :  _lnNBBJbQUaiITdI9niH_A,LDS:BoRV8ufsTfym0JlNGyeqcA"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "harness-nextgen, harness-nextgen-free, harness-nextgen-comp"
   },
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Evaluation Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(matched_url_path_rule, response_code) (rate(loadbalancing_googleapis_com:https_request_count{backend_target_name=~\"free-cf-client-backend\", forwarding_rule_name=\"prod-cf-https\"}[$__rate_interval]))",
     "legendFormat": "URL={{matched_url_path_rule}}, Code={{response_code}}"
    }
   ]
  },
  {
   "title": "Stream Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(matched_url_path_rule, response_code) (rate(loadbalancing_googleapis_com:https_request_count{backend_target_name=~\"free-pushpin-backend\", forwarding_rule_name=\"prod-cf-https\"}[$__rate_interval]))",
     "legendFormat": "URL={{matched_url_path_rule}}, Code={{response_code}}"
    }
   ]
  },
  {
   "title": "${AccountID:value} Request Rate By URL",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(url, method) (rate(ff_http_requests_total{url=~\"/api/1.0/admin/.*\", namespace=\"$namespace\", account=~\"${AccountID:value}\"}[$__rate_interval]))",
     "legendFormat": "url={{url}}"
    },
    {
     "expr": "sum by(url) (rate(ff_sdk_http_requests_total{namespace=\"$namespace\", account=~\"${AccountID:value}\"}[$__rate_interval]))",
     "legendFormat": "url={{url}}"
    }
   ]
  },
  {
   "title": "${AccountID:value} Request Rate By SDK",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(sdk, url) (rate(ff_sdk_http_requests_total{namespace=\"$namespace\", account=~\"${AccountID:value}\"}[$__rate_interval]))",
     "legendFormat": "sdk={{sdk}}, url={{url}}"
    }
   ]
  },
  {
   "title": "${AccountID:value} SDK Usage",
   "type": "timeseries",
   "description": "Shows which SDKs are being used",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(sdk_language, sdk_version, sdk_type) (rate(ff_metrics_service_sdk_count{namespace=\"harness-nextgen-free\", accountID=~\"${AccountID:value}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " SDK Usage Grouped By Account",
   "type": "timeseries",
   "description": "Shows which SDKs are being used",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by(sdk_language, sdk_version, sdk_type, accountID) (rate(ff_metrics_service_sdk_count{namespace=\"harness-nextgen-free\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SDK Evaluations By Day",
   "type": "barchart",
   "description": "Shows which SDKs are being used",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum by(sdk_type) (increase(ff_metrics_service_sdk_count{namespace=\"${namespace}\", accountID=~\"${AccountID:value}\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SDK Evaluations Per Month",
   "type": "stat",
   "description": "Shows which SDKs are being used",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(sdk_type) (increase(ff_metrics_service_sdk_count{namespace=\"${namespace}\", accountID=~\"${AccountID:value}\"}[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${AccountID:value} Connections per Day",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum by(url) (increase(ff_http_requests_total{url=~\"/api/1.0/client/auth\", namespace=\"$namespace\", account=~\"${AccountID:value}\", method=\"POST\", code=\"200\"}[24h]))",
     "legendFormat": "url={{url}}"
    }
   ]
  },
  {
   "title": "${AccountID:value} Connections last 30days",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(url) (increase(ff_http_requests_total{url=~\"/api/1.0/stream\", namespace=\"$namespace\", account=~\"${AccountID:value}\", code=\"200\", method=\"GET\"}[30d]))",
     "legendFormat": "url={{url}}"
    }
   ]
  },
  {
   "title": "${AccountID:value} Flags Created per Day",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum by(url) (increase(ff_http_requests_total{url=~\"/api/1.0/admin/features\", namespace=\"$namespace\", account=~\"${AccountID:value}\", method=\"POST\", code=\"201\"}[24h]))",
     "legendFormat": "url={{url}}"
    }
   ]
  },
  {
   "title": "${AccountID:value} Flags Created last 30d",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(url) (increase(ff_http_requests_total{url=~\"/api/1.0/admin/features\", namespace=\"$namespace\", account=~\"${AccountID:value}\", method=\"POST\", code=\"201\"}[30d]))",
     "legendFormat": "url={{url}}"
    }
   ]
  }
 ]
}