{
 "title": "Learning engine dashboard Free",
 "tags": [ "SRM" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "leTaskType",
    "label": "LE Task Type",
    "query": {
     "query": "label_values(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\"}, leTaskType)"
    }
   },
   { "name": "env", "label": "Env", "query": "free" },
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "LE tasks completion rate (count/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(custom_googleapis_com:opencensus_learning_engine_task_success_count{monitored_resource=\"k8s_container\",environment=\"$env\"}[5m])) by (environment) )",
     "legendFormat": "Success"
    },
    {
     "expr": "(sum(rate(custom_googleapis_com:opencensus_learning_engine_task_failed_count{monitored_resource=\"k8s_container\",environment=\"$env\"}[5m])) by (environment) )",
     "legendFormat": "Failed"
    },
    {
     "expr": "(sum(rate(custom_googleapis_com:opencensus_learning_engine_task_timeout_count{monitored_resource=\"k8s_container\",environment=\"$env\"}[5m])) by (environment) )",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "LE tasks queued count (max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(custom_googleapis_com:opencensus_learning_engine_task_queued_count{monitored_resource='k8s_container',environment=\"$env\"})",
     "legendFormat": "Overall queued"
    },
    {
     "expr": "max(custom_googleapis_com:opencensus_learning_engine_deployment_task_queued_count{monitored_resource='k8s_container',environment=\"$env\"})",
     "legendFormat": "Deployment queued"
    },
    {
     "expr": "max(custom_googleapis_com:opencensus_learning_engine_service_health_task_queued_count{monitored_resource='k8s_container',environment=\"$env\"})",
     "legendFormat": "Service health queued"
    }
   ]
  },
  {
   "title": "LE tasks max queued time (s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(max(custom_googleapis_com:opencensus_learning_engine_max_queued_time_free{monitored_resource=\"k8s_container\"}))/1000",
     "legendFormat": "Overall"
    },
    {
     "expr": "(max(custom_googleapis_com:opencensus_learning_engine_deployment_max_queued_time_free{monitored_resource=\"k8s_container\"}))/1000",
     "legendFormat": "Deployment"
    },
    {
     "expr": "(max(custom_googleapis_com:opencensus_learning_engine_service_health_max_queued_time_free{monitored_resource=\"k8s_container\"}))/1000",
     "legendFormat": "Service health"
    }
   ]
  },
  {
   "title": "LE tasks running count (max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(custom_googleapis_com:opencensus_learning_engine_task_running_count{monitored_resource='k8s_container',environment=\"$env\"})",
     "legendFormat": "Overall running"
    },
    {
     "expr": "max(custom_googleapis_com:opencensus_learning_engine_deployment_task_running_count{monitored_resource='k8s_container',environment=\"$env\"})",
     "legendFormat": "Deployment running"
    },
    {
     "expr": "max(custom_googleapis_com:opencensus_learning_engine_service_health_task_running_count{monitored_resource='k8s_container',environment=\"$env\"})",
     "legendFormat": "Service health running"
    }
   ]
  },
  {
   "title": "LE tasks completion count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(custom_googleapis_com:opencensus_learning_engine_task_success_count{monitored_resource=\"k8s_container\",environment=\"$env\"}) by (environment)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(custom_googleapis_com:opencensus_learning_engine_task_failed_count{monitored_resource=\"k8s_container\",environment=\"$env\"})by (environment)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(custom_googleapis_com:opencensus_learning_engine_task_timeout_count{monitored_resource=\"k8s_container\",environment=\"$env\"}) by (environment) ",
     "legendFormat": "Timeout"
    }
   ]
  },
  { "title": "LE Task Type Specific Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Number of tasks completed with different wait time buckets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"15000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"0\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "0-15 s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"30000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"15000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "15-30 s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"60000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"30000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"120000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"60000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "60-120s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"240000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"120000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "120-240s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"480000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"240000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "240-480s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"960000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"480000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "480-960s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"1920000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"960000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "960-1920s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"1920000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": ">1920s"
    }
   ]
  },
  {
   "title": "% of tasks completed with different wait time buckets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"15000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"0\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "0-15 s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"30000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"15000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "15-30 s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"60000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"30000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "30-60s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"120000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"60000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "60-120s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"240000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"120000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "120-240s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"480000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"240000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "240-480s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"960000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"480000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "480-960s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"1920000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"960000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "960-1920s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"1920000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_wait_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": ">1920s"
    }
   ]
  },
  {
   "title": "Number of tasks completed with different running time buckets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"15000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"0\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "0-15 s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"30000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"15000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "15-30 s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"60000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"30000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"120000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"60000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "60-120s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"240000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"120000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "120-240s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"480000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"240000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "240-480s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"960000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"480000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "480-960s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"1920000\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"960000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": "960-1920s"
    },
    {
     "expr": "(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}[5m])) by (environment))-(sum(increase(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"1920000\",environment=\"$env\"}[5m])) by (environment))",
     "legendFormat": ">1920s"
    }
   ]
  },
  {
   "title": "% of tasks completed with different running time buckets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"15000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"0\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "0-15 s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"30000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"15000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "15-30 s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"60000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"30000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "30-60s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"120000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"60000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "60-120s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"240000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"120000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "120-240s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"480000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"240000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "240-480s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"960000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"480000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "480-960s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"1920000\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"960000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": "960-1920s"
    },
    {
     "expr": "100*(((sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)) - (sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"1920000\",environment=\"$env\"}) by (environment)))/(sum(custom_googleapis_com:opencensus_learning_engine_task_running_time_bucket{monitored_resource=\"k8s_container\",leTaskType=\"$leTaskType\",le=\"+Inf\",environment=\"$env\"}) by (environment)))",
     "legendFormat": ">1920s"
    }
   ]
  }
 ]
}