{
 "title": "Anka Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Pipeline Concurrency ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TotalExecutions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(harness_ci_pipeline_execution_total{driver=\"ankabuild\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RunningExecutions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(namespace) (harness_ci_pipeline_running_executions{driver=\"ankabuild\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ExecutionsPerAccount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{os=\"darwin\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Anka Latency (50th)",
   "type": "timeseries",
   "description": "Thresholds 30,60,90,120 secs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le,namespace) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"ankabuild\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anka Latency (75th)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le,namespace) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"ankabuild\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anka Latency (90th)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le,namespace) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"ankabuild\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "MaxMemUsage[50th]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,namespace,location,pool_id) (rate(harness_ci_pipeline_max_mem_usage_percent_bucket{pool_id=\"linux-amd64\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MaxCpuUsage[50th]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,namespace) (rate(harness_ci_pipeline_max_cpu_usage_percent_bucket{pool_id=\"macos-arm64\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}