{
 "title": "BareMetal Dashboard",
 "tags": [
  "CIE",
  "Baremetal"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "GCP", "label": "GCP", "query": "GCP" },
   { "name": "Baremetal", "label": "nomad", "query": "Baremetal" }
  ]
 },
 "panels": [
  { "title": "Pipeline executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total pipeline executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pool_id) (increase(harness_ci_pipeline_execution_total{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pipeline executions (last day)",
   "type": "timeseries",
   "description": "aggregated daily",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pool_id) (increase(harness_ci_pipeline_execution_total[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pipeline executions (Google vs Baremetal)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{cluster=\"dlite-prod-us-west1-primary\",pool_id=\"linux-amd64-bare-metal\"}[$__range]))",
     "legendFormat": "Baremetal"
    },
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{cluster=\"dlite-prod-us-west1-primary\",pool_id!=\"linux-amd64-bare-metal\"}[$__range]))",
     "legendFormat": "Google"
    }
   ]
  },
  {
   "title": "Cumulative fallbacks from Baremetal to GCP",
   "type": "timeseries",
   "description": "Number of pipelines falling back to GCP due to baremetal rejections\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(new_namespace) (label_replace((harness_ci_pipeline_pool_fallbacks{pool_id=\"linux-amd64-bare-metal\"}), \"new_namespace\", \"$1\", \"pod\", \"([a-z]+-[a-z]+)-.*\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pipeline concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cluster wide",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (cluster) (harness_ci_pipeline_running_executions{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines per driver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(driver,os) (harness_ci_pipeline_running_executions)",
     "legendFormat": "{{driver}}->{{os}}"
    }
   ]
  },
  {
   "title": "Pipelines per owner_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(owner_id) (harness_ci_pipeline_per_account_running_executions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(new_namespace) (label_replace(harness_ci_pipeline_running_executions{}, \"new_namespace\", \"$1\", \"pod\", \"([a-z]+-[a-z]+)-.*\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Baremetal Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Baremetal pool usage (%)",
   "type": "timeseries",
   "description": "Red = 90%\nYellow = 75%\nBlue = 50%\n(sum by (driver) (harness_ci_pipeline_running_executions{state=\"inuse\",driver=\"nomad\"})/200)*100",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "(sum by(driver) (harness_ci_pipeline_running_executions{driver=\"nomad\"})/200)*100  ",
     "legendFormat": "Baremetal"
    }
   ]
  },
  {
   "title": "Baremetal requests that fallback to GCP as (%)",
   "type": "timeseries",
   "description": "Threshold 3, 6, 9, 12 %\n\n(sum(harness_ci_pipeline_pool_fallbacks{pool_id=\"linux-amd64-bare-metal\"})/sum(harness_ci_pipeline_execution_total{driver=\"nomad\"}))*100",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "(100%sum(harness_ci_pipeline_pool_fallbacks{pool_id=\"linux-amd64-bare-metal\"})/sum(harness_ci_pipeline_execution_total{driver=\"nomad\"}))",
     "legendFormat": "nomad"
    }
   ]
  },
  {
   "title": "Baremetal fallback requests per minute",
   "type": "timeseries",
   "description": "Number of pipelines falling back to GCP per m\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum by(new_namespace) (label_replace(increase(harness_ci_pipeline_pool_fallbacks{pool_id=\"linux-amd64-bare-metal\"}[1m]), \"new_namespace\", \"$1\", \"pod\", \"([a-z]+-[a-z]+)-.*\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "GCP Latency (90th)",
   "type": "timeseries",
   "description": "Thresholds 120, 180, 240, 300 secs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le,namespace,location,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver!=\"nomad\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "Nomad Latency (90th)",
   "type": "timeseries",
   "description": "Thresholds 30,60,90,120 secs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le,namespace,location,pool_id) (rate(\n    harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\"}[$__rate_interval])))",
     "legendFormat": "{{location}}/{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "GCP Latency (75th)",
   "type": "timeseries",
   "description": "Thresholds 120, 180, 240, 300 secs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le,namespace,location,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"google\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nomad Latency (75th)",
   "type": "timeseries",
   "description": "Thresholds 30,60,90,120 secs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le,namespace,location,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\"}[$__rate_interval])))",
     "legendFormat": "{{location}}/{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "GCP Latency (50th)",
   "type": "timeseries",
   "description": "Thresholds 120, 180, 240, 300 secs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le,namespace,location,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"google\"}[$__rate_interval])))",
     "legendFormat": "{{location}}/{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "Nomad Latency (50th)",
   "type": "timeseries",
   "description": "Thresholds 30,60,90,120 secs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le,namespace,location,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\"}[$__rate_interval])))",
     "legendFormat": "{{location}}/{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "Pipeline failures due to system",
   "type": "timeseries",
   "description": "sum by(driver) (((harness_ci_pipeline_execution_errors_total{}) / harness_ci_pipeline_execution_total)*100)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by(driver,pool_id) (((harness_ci_pipeline_execution_errors_total{}) / harness_ci_pipeline_execution_total)*100)",
     "legendFormat": "{{driver}}->{{pool_id}}"
    }
   ]
  }
 ]
}