{
 "title": "Access Control Entity Metrics",
 "tags": [ "0compatible" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(outbox_event_processing_time_sum,cluster)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(outbox_event_processing_time_sum,environment)"
    }
   },
   { "name": "redis_namespace", "label": "redis_namespace", "query": "prod , freemium , compliance" }
  ]
 },
 "panels": [
  {
   "title": "Redis Consumer Group Behind from Stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(usecaseName, consumergroupName) (custom_googleapis_com:opencensus_redis_streams_consumer_group_behind_by_count{monitored_resource=\"k8s_container\",cluster_name=\"$cluster\", namespace=\"$redis_namespace\", consumergroupName=\"accessControlService\"})",
     "legendFormat": "{{usecaseName}} [ {{consumergroupName}} ]"
    }
   ]
  },
  {
   "title": "Consumer Group Pending Count for Stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(usecaseName, consumergroupName) (custom_googleapis_com:opencensus_redis_streams_consumer_group_pending_count{monitored_resource=\"k8s_container\" , cluster_name=\"$cluster\", namespace=\"$redis_namespace\", consumergroupName=\"accessControlService\"})",
     "legendFormat": "{{usecaseName}} [ {{consumergroupName}} ]"
    }
   ]
  },
  {
   "title": "outbox_entries_processing_time_by_event_type (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(eventType,environment) (rate(outbox_event_processing_time_sum{ serviceId=\"accessControlService\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "outbox_entries_delay_by_resource_type (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(resourceType,environment) (rate(outbox_event_waiting_time_sum{serviceId=\"accessControlService\",environment=~\"$environment\"}[1m]))",
     "legendFormat": "{{resourceType}}"
    }
   ]
  }
 ]
}