{
 "title": "Access Control HTTP Metrics",
 "tags": [ "0compatible" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kubernetes_io:container_uptime{container_name=~\"access-control.*\"},cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubernetes_io:container_uptime{container_name=~\"access-control.*\" , cluster_name=\"$cluster\"},namespace_name)"
    }
   },
   {
    "name": "resource",
    "label": "resource",
    "query": {
     "query": "label_values(io_harness_resources_responses_count{cluster=\"$cluster\", serviceName=\"access-control\"},resource)"
    }
   },
   { "name": "statusCode", "label": "statusCode", "query": "1xx , 2xx , 3xx , 4xx , 5xx" }
  ]
 },
 "panels": [
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All APIs Request Rate [ Service Load ]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(serviceName , namespace) (rate(io_harness_resources_responses_count{cluster=\"$cluster\", namespace=\"$namespace\", serviceName=\"access-control\"}[5m]))",
     "legendFormat": "{{serviceName}} [{{namespace}}]"
    }
   ]
  },
  {
   "title": "Access Control Prod Alerts [ Current State ]",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max by(method, resource) (io_harness_resources_responses_latency_snapshot_95thPercentile{cluster=\"$cluster\", namespace=\"$namespace\", serviceName=\"access-control\"}) > 1",
     "legendFormat": "{{resource}} [{{method}}]"
    }
   ]
  },
  {
   "title": "Top Slowest APIs > 1s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(method, resource) (io_harness_resources_responses_latency_snapshot_95thPercentile{cluster=\"$cluster\", namespace=\"$namespace\", serviceName=\"access-control\"}) > 1",
     "legendFormat": "{{resource}} [{{method}}]"
    }
   ]
  },
  { "title": "$resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$resource APIs Request Rate [ Resource Load ]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(resource , namespace) (rate(io_harness_resources_responses_count{cluster=\"$cluster\", namespace=\"$namespace\", serviceName=\"access-control\" , resource=\"$resource\"}[5m]))",
     "legendFormat": "{{resource}} [{{namespace}}]"
    }
   ]
  },
  {
   "title": "$resource APIs $statusCode %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{cluster='$cluster',serviceName='access-control' , resource=\"$resource\" , namespace='$namespace' , statusCode='$statusCode'}[5m]))*100) \n/ \n(sum by(method) \n(rate(io_harness_resources_responses_count{cluster='$cluster',serviceName='access-control' , resource=\"$resource\" , namespace='$namespace'}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "$resource P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (method)(io_harness_resources_responses_latency_snapshot_95thPercentile{cluster='$cluster',resource=\"$resource\" , namespace='$namespace'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "$resource P99 ART",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (method)(io_harness_resources_responses_latency_snapshot_99thPercentile{cluster='$cluster',resource=\"$resource\" , namespace='$namespace'})",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}