{
 "title": "Delegate tasks",
 "tags": [ "0compatible" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values({__name__=\"active_delegate_count\"},environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=\"active_delegate_count\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "active_delegate_task",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(delta(active_delegate_task{cluster=\"$cluster\", environment=\"$env\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "delegate_task_creation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(delegate_task_creation_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "delegate_task_creation_by_type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(taskType) (delta(delegate_task_creation_by_type_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "delegate_task_acquire",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(delta(delegate_task_acquire_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "delegate_response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(delegate_response_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "delegate_task_rebroadcast",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(delta(delegate_task_rebroadcast_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "delegate_task_expired",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(delta(delegate_task_expired_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "delegate_task_no_eligible_delegates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(delegate_task_no_eligible_delegates_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}