{
 "title": "Delegates Summary",
 "tags": [ "0compatible" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(active_delegate_count,cluster)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(active_delegate_count,environment)"
    }
   },
   {
    "name": "accountId",
    "label": "AccountId",
    "query": {
     "query": "label_values(delegate_registration_total{cluster=\"$cluster\", environment=\"$env\"},accountId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "delegate_registration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(delegate_registration_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "Delegate Registrations"
    }
   ]
  },
  {
   "title": "delegate_registration_failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(delegate_registration_failed_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "Delegate Failed Registrations"
    }
   ]
  },
  {
   "title": "delegate_restarted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(delta(delegate_restarted_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "Delegate Restarts"
    }
   ]
  },
  {
   "title": "active_delegate_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(active_delegate_count{cluster=\"$cluster\", environment=\"$env\"})",
     "legendFormat": "Active Delegate Count"
    }
   ]
  },
  {
   "title": "delegate_disconnected_rate (avg of all accounts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(delta(delegate_disconnected_total{cluster=\"$cluster\", environment=\"$env\"}[10m]))",
     "legendFormat": "Delegate Disconnected"
    }
   ]
  },
  {
   "title": "delegate_disconnected_rate (per account)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "max by(environment) (delta(delegate_disconnected_total{cluster=\"$cluster\", environment=\"$env\", accountId=\"$accountId\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "websocket_connections_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "count by(container_name) (websocket_connections_count{cluster=\"$cluster\", environment=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "immutable_delegate_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "max(immutable_delegate{cluster=\"$cluster\", environment=\"$env\"})",
     "legendFormat": "Immutable Delegate Count"
    }
   ]
  },
  {
   "title": "active_delegate_process_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "count by(container_name) (active_delegate_process_count{cluster=\"$cluster\", environment=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Delegate Tasks Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "max(active_delegate_task{cluster=\"$cluster\", environment=\"$env\"})",
     "legendFormat": "Active Delegate Tasks"
    }
   ]
  }
 ]
}