{
 "title": "Iterator Metrics",
 "tags": [ "0compatible" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(iterator_working_on_entity_total,cluster)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(iterator_working_on_entity_total,environment)"
    }
   },
   {
    "name": "iteratorName",
    "label": "IteratorName",
    "query": {
     "query": "label_values(iterator_working_on_entity_total{cluster=\"$cluster\",environment=\"$environment\"},iteratorName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "iterator_working_on_entity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(environment) (rate(iterator_working_on_entity_total{cluster=\"$cluster\", environment=\"$environment\", iteratorName=\"$iteratorName\"}[3h]))",
     "legendFormat": "Working on Entity Rate"
    }
   ]
  },
  {
   "title": "iterator_delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(environment) (histogram_quantile(0.5, delta(iterator_delay_bucket{cluster=\"$cluster\", environment=\"$environment\", iteratorName=\"$iteratorName\"}[3h])))",
     "legendFormat": "Delay"
    }
   ]
  },
  {
   "title": "iterator_processing_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(environment) (histogram_quantile(0.5, delta(iterator_processing_time_bucket{cluster=\"$cluster\", environment=\"$environment\", iteratorName=\"$iteratorName\"}[3h])))",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "iterator_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(iteratorName) (iterator_error_total{cluster=\"$cluster\", environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}