{
 "title": "ScopeInfo Resource HTTP",
 "tags": [ "0compatible" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kubernetes_io:container_uptime{container_name=~\"ng-manager.*\"},cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(io_harness_resources_responses_count{resource=\"ScopeInfoResource\"},namespace)"
    }
   },
   { "name": "statusCode", "query": "1xx , 2xx , 3xx , 4xx , 5xx" }
  ]
 },
 "panels": [
  {
   "title": "ScopeInfoResource API $statusCode Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{cluster='$cluster',serviceName='ng-manager' , resource=\"ScopeInfoResource\" , namespace='$namespace' , statusCode='$statusCode'}[5m]))*100) \n/ \n(sum by(method) \n(rate(io_harness_resources_responses_count{cluster='$cluster',serviceName='ng-manager' , resource=\"ScopeInfoResource\" , namespace='$namespace'}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ScopeInfoResource API P95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (method)(io_harness_resources_responses_latency_snapshot_95thPercentile{cluster='$cluster',resource=\"ScopeInfoResource\" , namespace='$namespace'})",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "ScopeInfoResource API P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (method)(io_harness_resources_responses_latency_snapshot_99thPercentile{cluster='$cluster',resource=\"ScopeInfoResource\" , namespace='$namespace'})",
     "legendFormat": "{{environment}}"
    }
   ]
  }
 ]
}