{
 "title": "System Observability Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(io_dropwizard_jetty_MutableServletContextHandler_4xx_responses_count, environment)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(io_dropwizard_jetty_MutableServletContextHandler_4xx_responses_count{environment=\"$env\"}, serviceName)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(io_dropwizard_jetty_MutableServletContextHandler_4xx_responses_count{environment=\"$env\", serviceName=\"$service\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(io_dropwizard_jetty_MutableServletContextHandler_4xx_responses_count{serviceName =\"$service\", environment=\"$env\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mean Error Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(job) (io_dropwizard_jetty_MutableServletContextHandler_4xx_responses_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "4xx_Count"
    },
    {
     "expr": "sum by(job) (io_dropwizard_jetty_MutableServletContextHandler_5xx_responses_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "5xx_Count"
    },
    {
     "expr": "sum by(job) (io_dropwizard_jetty_MutableServletContextHandler_requests_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Total_Count"
    }
   ]
  },
  {
   "title": "Mean Response Time (95%)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(environment) (io_dropwizard_jetty_MutableServletContextHandler_requests_snapshot_95thPercentile{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "99.9%"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(environment) (delta(io_dropwizard_jetty_MutableServletContextHandler_4xx_responses_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "4xx Count"
    },
    {
     "expr": "sum by(environment) (delta(io_dropwizard_jetty_MutableServletContextHandler_5xx_responses_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "5xx Count"
    },
    {
     "expr": "sum by(environment) (delta(io_dropwizard_jetty_MutableServletContextHandler_requests_count{environment=\"$env\", serviceName=\"$service\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "Total Count"
    }
   ]
  },
  {
   "title": "HTTP Response 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum by(environment) (io_dropwizard_jetty_MutableServletContextHandler_requests_snapshot_95thPercentile{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "95th percentile snapshot"
    }
   ]
  },
  {
   "title": "HTTP Error Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(environment) (delta(io_dropwizard_jetty_MutableServletContextHandler_4xx_responses_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "4xx Count in last 5 mins"
    },
    {
     "expr": "sum by(environment) (delta(io_dropwizard_jetty_MutableServletContextHandler_5xx_responses_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "5xx Count in last 5 mins"
    }
   ]
  },
  {
   "title": "HTTP Response 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg by(environment) (io_dropwizard_jetty_MutableServletContextHandler_requests_snapshot_99thPercentile{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "99th percentile snapshot"
    },
    {
     "expr": "avg by(environment) (io_dropwizard_jetty_MutableServletContextHandler_requests_snapshot_999thPercentile{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "99.9th percentile snapshot"
    }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(io_dropwizard_jetty_MutableServletContextHandler_requests_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"}[5m])) by (environment)",
     "legendFormat": "$service: $env"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Committed, Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(environment) (jvm_memory_non_heap_used{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by(environment) (jvm_memory_non_heap_committed{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Total Memory Max, Committed, Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(environment) (jvm_memory_total_max{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum by(environment) (jvm_memory_total_committed{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum by(environment) (jvm_memory_total_used{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "JVM Metaspace Memory Pool Used, Committed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(environment) (jvm_memory_pools_Metaspace_used{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by(environment) (jvm_memory_pools_Metaspace_committed{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Heap Max, Committed, Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(environment) (jvm_memory_heap_max{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum by(environment) (jvm_memory_heap_committed{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum by(environment) (jvm_memory_heap_used{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(environment) (jvm_threads_runnable_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Runnable"
    },
    {
     "expr": "sum by(environment) (jvm_threads_timed_waiting_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Timed Waiting"
    },
    {
     "expr": "sum by(environment) (jvm_threads_waiting_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "JVM Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(environment) (jvm_threads_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Threads count"
    },
    {
     "expr": "sum by(environment) (jvm_threads_daemon_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Daemon Threads Count"
    },
    {
     "expr": "sum by(environment) (jvm_threads_peak_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Peak Threads Count"
    }
   ]
  },
  {
   "title": "DW Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(environment) (org_eclipse_jetty_util_thread_QueuedThreadPool_dw_size{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Threads servicing requests"
    }
   ]
  },
  {
   "title": "JVM Threads Blocked / Deadlock State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(environment) (jvm_threads_blocked_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum by(environment) (jvm_threads_deadlock_count{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Deadlock"
    }
   ]
  },
  {
   "title": "Nos of Queued DW Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(environment) (org_eclipse_jetty_util_thread_QueuedThreadPool_dw_jobs{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Queued Jobs waiting for DW Thread"
    }
   ]
  },
  {
   "title": "DW Threads Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(environment) (org_eclipse_jetty_util_thread_QueuedThreadPool_dw_utilization{environment=\"$env\", serviceName=\"$service\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Thread Utilization %"
    }
   ]
  }
 ]
}