{
 "title": "Queue Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Enqueue / Dequeue requests per module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(enqueue_requests_per_module_success{topic=\"ci\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(dequeue_requests_per_module_success{topic=\"ci\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(dequeue_requests_per_module_failure{topic=\"ci\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(enqueue_requests_per_module_failure{topic=\"ci\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue/ Ack/ Dequeue Requests Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{url=\"/v1/queue\", le=\"+Inf\", code!=\"200\"}[5m]))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{url=\"/v1/ack\", le=\"+Inf\", code=\"400\" }[5m]))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{url=\"/v1/dequeue\", le=\"+Inf\", code=\"400\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue/ Ack/ Dequeue Requests TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{url=\"/v1/queue\", le=\"+Inf\", code=\"200\"}[5m]))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{url=\"/v1/ack\", le=\"+Inf\", code=\"200\"}[5m]))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{url=\"/v1/dequeue\", le=\"+Inf\", code=\"200\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue/ Ack/ Dequeue Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{url=\"/v1/dequeue\", le=\"+Inf\", code=\"200\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue/ Ack/ Dequeue Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(echo_request_duration_seconds_bucket{url=\"/v1/queue\", code=\"200\"}[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(echo_request_duration_seconds_bucket{url=\"/v1/ack\", code=\"200\"}[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(echo_request_duration_seconds_bucket{url=\"/v1/dequeue\", code=\"200\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}