{
 "title": "Anka Dashboard",
 "tags": [ "0compatible" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "label": "dataSource", "query": "prometheus" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(up{},cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Anka Pipelines Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{cluster=\"$Cluster\",driver=\"ankabuild\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Machines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{cluster=\"$Cluster\",os=\"darwin\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency (secs)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(harness_ci_runner_wait_duration_seconds_bucket{cluster=\"$Cluster\",driver=\"ankabuild\",pool_id=\"macos-arm64\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Concurrency ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "TotalExecutions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(label_replace(\n  increase(harness_ci_pipeline_execution_total{driver=\"ankabuild\",cluster=\"$Cluster\"}[$__interval]),\n  \"new_namespace\", \"$1\", \"pod\", \"([a-z]+-[a-z]+)-.*\"\n)\n) by (new_namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RunningExecutions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "sum by(new_namespace) (label_replace(harness_ci_pipeline_running_executions{cluster=\"$Cluster\", driver=\"ankabuild\",state=\"inuse\"}, \"new_namespace\", \"$1\", \"pod\", \"([a-z]+-[a-z]+)-.*\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RunningExecutions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "sum by(new_namespace) (label_replace(harness_ci_pipeline_running_executions{cluster=\"$Cluster\", driver=\"ankabuild\",state=\"inuse\"}, \"new_namespace\", \"$1\", \"pod\", \"([a-z]+-[a-z]+)-.*\"))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg latency(p50) (per customer)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le,owner_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{cluster=\"$Cluster\",driver=\"ankabuild\",is_fallback=\"false\"}[1h])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg latency(p95) (per customer)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le,owner_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{cluster=\"$Cluster\",driver=\"ankabuild\",is_fallback=\"false\"}[1h])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "k8S Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "MaxMemUsage[50th]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le,namespace,location,pool_id) (rate(harness_ci_pipeline_max_mem_usage_percent_bucket{pool_id=\"macos-arm64\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MaxCpuUsage[50th]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le,namespace) (rate(harness_ci_pipeline_max_cpu_usage_percent_bucket{pool_id=\"macos-arm64\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}