{
 "title": "BareMetal Dashboard",
 "tags": [
  "CIE",
  "Baremetal",
  "0compatible"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dataSource", "label": "dataSource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up{},cluster)" } }
  ]
 },
 "panels": [
  { "title": "Pipeline concurrency - Active", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operating System",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,os) (harness_ci_pipeline_running_executions{state=\"inuse\"})",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "Pool",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,pool_id) (harness_ci_pipeline_running_executions{state=\"inuse\"})",
     "legendFormat": "{{pool_id}}"
    }
   ]
  },
  {
   "title": "Account",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(new_namespace) (label_replace(harness_ci_pipeline_running_executions{}, \"new_namespace\", \"$1\", \"pod\", \"([a-z]+-[a-z]+[0-9]*)-.*\"))",
     "legendFormat": "{{new_namespace}}"
    }
   ]
  },
  {
   "title": "Pipelines per driver",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(driver,os) (harness_ci_pipeline_running_executions)",
     "legendFormat": "{{driver}}->{{os}}"
    }
   ]
  },
  {
   "title": "Pipelines per namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace,new_namespace) (label_replace(harness_ci_pipeline_running_executions{}, \"new_namespace\", \"$1\", \"pod\", \"([a-z]+-[a-z]+[0-9]*)-.*\"))",
     "legendFormat": "{{namespace}}->{{new_namespace}}"
    }
   ]
  },
  {
   "title": "Pipelines per owner_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available capacity per account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "500 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"ngDRzuBUQZGu6HZ6SxEDXQ\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "200 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"vpCkHKsDSxK9_KYfjCTMKA\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"TkD5TecxSsWa0sknd5crgw\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"6P8wiTFqSPul99qcIkRUNQ\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "80 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"Q8_q5d7BQy-0iAh0D8klTw\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "200 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"VRuJ8-dqQH6QZgAtoBr66g\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "90 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"uHZJN3pqSdORjA0KQA2kWw\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "90 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"hkoy5u-KQ3yxv6wafu9_Mg\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "200 - (sum by(owner_id) (harness_ci_pipeline_per_account_running_executions{owner_id=\"l7B_kbSEQD2wjrM7PShm5w\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Baremetal Usage - Active", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Baremetal pool used (%)",
   "type": "timeseries",
   "description": "Red = 90%\nYellow = 75%\nBlue = 50%\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "(sum by(driver) (harness_ci_pipeline_running_executions{driver=\"nomad\"}/654))*100",
     "legendFormat": "Baremetal"
    }
   ]
  },
  {
   "title": "Baremetal fallback requests (15m rolling window)",
   "type": "timeseries",
   "description": "Number of pipelines falling back to GCP per m\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": " (sum by(namespace,owner_id) (increase(harness_ci_pipeline_pool_fallbacks{pool_id=\"linux-amd64-bare-metal\",}[15m]))) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(driver) (harness_ci_pipeline_running_executions{driver=\"nomad\"}/488))*100 >= 100",
     "legendFormat": "NomadPool"
    }
   ]
  },
  { "title": "Latency - Active", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "options": {
    "content": "<table style=\"border-collapse: separate; width: 100%; background-color: #008000;\">\n    <tr>\n        <td style=\"border: 12px solid white; text-align: center; padding: 10px;\">\n            <div style=\"margin: 22px; color: white;\">Average init time (p50)</div>\n        </td>\n    </tr>\n   \n   "
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "options": {
    "content": "<table style=\"border-collapse: separate; width: 100%; background-color:  #F08080;\">\n    <tr>\n        <td style=\"border: 12px solid white; text-align: center; padding: 10px;\">\n            <div style=\"margin: 22px; color: white;\">Worst case init time (p95)</div>\n        </td>\n    </tr>\n   \n   "
   }
  },
  {
   "title": "Baremetal - linux-amd64 ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\",pool_id=\"linux-amd64-bare-metal\",is_fallback=\"false\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"google\",pool_id=~\"linux-amd64|linux-arm64|windows-amd64|windows-free-amd64\",is_fallback=\"false\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tartbuild-M2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\",pool_id=\"macos-arm64-tart\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Baremetal - linux-amd64",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\",pool_id=\"linux-amd64-bare-metal\",is_fallback=\"false\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"google\",pool_id=~\"linux-amd64|linux-arm64|windows-amd64|windows-free-amd64\",is_fallback=\"false\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tartbuild-M2-MacOS ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\",pool_id=\"macos-arm64-tart\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg latency(p50) (no fallback) > 30s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,owner_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\",pool_id=\"linux-amd64-bare-metal\",is_fallback=\"false\"}[1h]))) > 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency(p95) (no fallback) > 120s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,owner_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\",pool_id=\"linux-amd64-bare-metal\",is_fallback=\"false\"}[1h]))) > 120",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg latency(p50) (fallback) > 30s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,owner_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\",pool_id=\"linux-amd64-bare-metal\",is_fallback=\"true\"}[1h]))) > 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency(p95) (fallback) > 120s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,owner_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\",pool_id=\"linux-amd64-bare-metal\",is_fallback=\"true\"}[1h]))) > 120",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GCP Latency (50th)",
   "type": "timeseries",
   "description": "Thresholds 120, 180, 240, 300 secs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le,namespace,location,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"google\"}[$__rate_interval])))",
     "legendFormat": "{{location}}/{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "GCP Latency (90th)",
   "type": "timeseries",
   "description": "Thresholds 120, 180, 240, 300 secs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le,namespace,location,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver!=\"nomad\"}[$__rate_interval])))",
     "legendFormat": "{{location}}/{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "Nomad Latency (50th)",
   "type": "timeseries",
   "description": "Thresholds 30,60,90,120 secs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le,namespace,location,pool_id) (rate(harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\"}[$__rate_interval])))",
     "legendFormat": "{{location}}/{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "Nomad Latency (90th)",
   "type": "timeseries",
   "description": "Thresholds 30,60,90,120 secs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le,namespace,location,pool_id) (rate(\n    harness_ci_runner_wait_duration_seconds_bucket{driver=\"nomad\"}[$__rate_interval])))",
     "legendFormat": "{{location}}/{{namespace}}/{{pool_id}}"
    }
   ]
  },
  {
   "title": "Pipeline failures due to system (15m rolling)",
   "type": "timeseries",
   "description": "sum by(driver) (((harness_ci_pipeline_execution_errors_total{}) / harness_ci_pipeline_execution_total)*100)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by(driver,pool_id) (increase(harness_ci_pipeline_execution_errors_total{}[15m]))",
     "legendFormat": "{{driver}}->{{pool_id}}"
    }
   ]
  },
  {
   "title": "Pipeline executions - Completed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 }
  },
  {
   "title": "Total pipeline executions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Baremetal Pipelines Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{driver=\"nomad\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Pipelines Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{driver=\"google\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tart M2 pipelines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{driver=\"nomad\", pool_id=\"macos-arm64-tart\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fallbacks (max)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_pool_fallbacks[$__range]))",
     "legendFormat": "Fallbacks"
    }
   ]
  },
  {
   "title": "Total pipeline executions (baremetal)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum by (owner_id) (increase(harness_ci_pipeline_execution_total{driver=\"nomad\"}[$__range]))",
     "legendFormat": "{{owner_id}}"
    }
   ]
  },
  {
   "title": "Total pipeline executions",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "sum by (owner_id) (increase(harness_ci_pipeline_execution_total{}[$__range]))",
     "legendFormat": "{{owner_id}}"
    }
   ]
  },
  {
   "title": "Total pipeline executions (6hr range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum by(pool_id) (increase(harness_ci_pipeline_execution_total{}[6h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pipeline executions (1d range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "sum by(pool_id) (increase(harness_ci_pipeline_execution_total{}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pipeline executions (Google vs Baremetal) (6h range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{pool_id=\"linux-amd64-bare-metal\"}[6h]))",
     "legendFormat": "Baremetal"
    },
    {
     "expr": "sum by(cluster) (increase(harness_ci_pipeline_execution_total{pool_id!=\"linux-amd64-bare-metal\"}[6h]))",
     "legendFormat": "Google"
    }
   ]
  },
  {
   "title": "Total pipeline executions (by namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(harness_ci_pipeline_execution_total{pool_id=\"linux-amd64-bare-metal\"}[6h])>0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Google Pipelines Contribution (%) (6 hr range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "100*(\n    sum by(owner_id) (\n        increase(harness_ci_pipeline_execution_total{driver=\"google\",pool_id=~\"linux-amd64.*\"}[6h]) > 5\n    ) \n    / \n    sum by(owner_id) (\n        increase(harness_ci_pipeline_execution_total{pool_id=~\"linux-amd64.*\"}[6h])\n    )\n) ",
     "legendFormat": "{{owner_id}}"
    }
   ]
  },
  {
   "title": "Fallbacks (by owner_id) (6hr range)",
   "type": "timeseries",
   "description": "Number of pipelines falling back to GCP due to baremetal rejections\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum by(owner_id) (increase(harness_ci_pipeline_pool_fallbacks{}[6h]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Consumers - Baremetal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum by(owner_id) (increase(harness_ci_pipeline_execution_total{driver=\"nomad\"}[15m])) > .001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Consumers - Google",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 131 },
   "targets": [
    {
     "expr": "topk(5, sum by(owner_id) (increase(harness_ci_pipeline_execution_total{driver=\"google\"}[15m]))) > .001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Consumers - Tart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 131 },
   "targets": [
    {
     "expr": "topk(5, sum by(owner_id) (increase(harness_ci_pipeline_execution_total{driver=\"nomad\",pool_id=\"macos-arm64-tart\"}[15m])>0))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}