{
 "title": "CCM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "lightwing|harness-nextgen|harness, lightwing-free|harness-nextgen-free|harness-free"
   }
  ]
 },
 "panels": [
  {
   "title": "Visibility Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - ce-nextgen",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"ce-nextgen\"}",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"ce-nextgen\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Utilization - ce-nextgen",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"ce-nextgen\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"ce-nextgen\"})",
       "legendFormat": "Memory_Limit"
      }
     ]
    },
    {
     "title": "CPU - batch-processing",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "max by(container_name) (kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"batch-processing\"})",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"batch-processing\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Utilization - batch-processing",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"batch-processing\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"batch-processing\"})",
       "legendFormat": "Memory_Limit"
      }
     ]
    },
    {
     "title": "CPU - anomaly-detection",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "max by(container_name) (kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"anomaly-detection\"})",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"anomaly-detection\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Utilization - anomaly-detection",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"anomaly-detection\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"anomaly-detection\"})",
       "legendFormat": "Memory_Limit"
      }
     ]
    },
    {
     "title": "CPU - ng-ce-ui",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "max by(container_name) (kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"ng-ce-ui\"})",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"ng-ce-ui\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Utilization - ng-ce-ui",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"ng-ce-ui\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
       "legendFormat": "{{pod_name}}"
      },
      {
       "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"ng-ce-ui\"})",
       "legendFormat": "Memory_Limit"
      }
     ]
    }
   ]
  },
  { "title": "Optimization Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Cpu Utilization - Faktory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"faktory\"}",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"faktory\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization - Faktory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"faktory\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"faktory\"})",
     "legendFormat": "Memory_Limit"
    }
   ]
  },
  {
   "title": "CPU - lwd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(container_name) (kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"lwd\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"lwd\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization - lwd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"lwd\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"lwd\"})",
     "legendFormat": "Memory_Limit"
    }
   ]
  },
  {
   "title": "CPU - worker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(container_name) (kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"worker\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"worker\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization - worker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"worker\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"worker\"})",
     "legendFormat": "Memory_Limit"
    }
   ]
  },
  {
   "title": "CPU - Gov Worker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(container_name) (kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"ccm-worker\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"ccm-worker\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization - Gov Worker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"ccm-worker\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"ccm-worker\"})",
     "legendFormat": "Memory_Limit"
    }
   ]
  },
  {
   "title": "CPU - DKron",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(container_name) (kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"ccm-dkron\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"ccm-dkron\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization - DKron",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"ccm-dkron\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"ccm-dkron\"})",
     "legendFormat": "Memory_Limit"
    }
   ]
  },
  {
   "title": "CPU - Commitment Orch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(container_name) (kubernetes_io:container_cpu_request_cores{namespace_name=~\"$cluster\", container_name=\"lwd-autocud\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "kubernetes_io:container_cpu_limit_utilization{namespace_name=~\"$cluster\", container_name=\"lwd-autocud\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization - Commitment Orch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (kubernetes_io:container_memory_used_bytes{container_name=\"lwd-autocud\", namespace_name=~\"$cluster\", memory_type=\"non-evictable\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by(namespace_name) (kubernetes_io:container_memory_limit_bytes{namespace_name=~\"$cluster\", container_name=\"lwd-autocud\"})",
     "legendFormat": "Memory_Limit"
    }
   ]
  }
 ]
}