{
 "title": "Operational Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "lightwing|harness-nextgen|harness, lightwing-free|harness-nextgen-free|harness-free"
   }
  ]
 },
 "panels": [
  {
   "title": "Warmup Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(ccm_lw_as_warmup_total{namespace=~\"$cluster\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cooldown Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(ccm_lw_as_cooldown_total{namespace=~\"$cluster\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Background Job Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ccm_lw_job_waiting_time{namespace=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Requests/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(code) (increase(ccm_lw_http_requests_completed{namespace=~\"$cluster\"}[1s]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "AutoStopping Rule Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(operation, account_id) (increase(ccm_lw_as_rule_operation_error_total{namespace=~\"$cluster\"}[10m]))",
     "legendFormat": "{{account_id}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Faktory Job Processed (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(namespace) (increase(ccm_lw_job_success_total{namespace=~\"$cluster\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}