{
 "title": "Delegate Admin Board",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "DataSource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(heartbeat_received,environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(heartbeat_received,cluster)"
    }
   },
   {
    "name": "account_id",
    "label": "AcccountID",
    "query": {
     "query": "label_values(heartbeat_received{environment=\"$env\", cluster=\"$cluster\"},accountId)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Ring information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "heartbeat_received{cluster=\"$cluster\", environment=\"$env\", accountId=~\"$account_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Delegates List",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "heartbeat_received{delegateConnectionStatus=\"CONNECTED\", environment=\"$env\", accountId=~\"$account_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delegate Event",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "heartbeat_received{accountId=~\"$account_id\", environment=\"$env\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delegate Upgrade History",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "heartbeat_received{accountId=~\"$account_id\", environment=\"$env\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}