{
 "title": "Generic Infra Monitoring Dashboard",
 "description": "Dashboard for Monitoring daily health of the services",
 "tags": [
  "PL",
  "CAE",
  "Platform",
  "weekly-monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "container",
    "label": "Container",
    "query": "access-control , platform-service , manager-iterator , manager , ng-manager , gateway , ng-dashboard-aggregator , audit-event-streaming , chatbot-service , redis-streams-monitor , ng-auth-ui , genai-service , agent-gateway"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{container=~\"$container\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pods",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", container=\"$container\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$container Memory Util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", container=~\"$container.*\", pod=~\"$pod\"}) by(namespace, pod, container)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=~\"$namespace\", container=~\"$container.*\", pod=~\"$pod\"}) by (namespace, pod, container)",
     "legendFormat": "Limit/{{pod}}"
    }
   ]
  },
  {
   "title": "$container CPU util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"$container.*\", pod=~\"$pod\", resource=\"cpu\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(namespace, container) (kube_pod_container_status_running{namespace=~\"$namespace\", container=~\"$container.*\", pod=~\"$pod\"} > 0)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(namespace, container) (increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", container=~\"$container.*\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Image version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (namespace, container, image_spec, version) (label_replace(kube_pod_container_info{namespace=~\"$namespace\", container=~\"$container\"}, \"version\", \"$1\", \"image_spec\", \".*/([0-9a-z-]+[:@].*)\")) * 0 + 1",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}