{
 "title": "Platform SLIs",
 "tags": [
  "sli",
  "platfom",
  "PL",
  "SLI"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "status", "label": "Status", "query": "1xx , 2xx , 3xx , 4xx , 5xx" }
  ]
 },
 "panels": [
  {
   "title": "Prod-1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AccountResource', environment='prod', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AccountResource', environment='prod'}[5m])))\n",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource='ServiceAccountResource', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource='ServiceAccountResource'}[5m])))\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Account APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='prod', resource='AccountResource', method!~\"getAccountDetails\"}) # PL-51554for more details on exclusion of methods",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{serviceName='ng-manager', environment='prod', resource='ServiceAccountResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Login APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'UserResource', environment='prod', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='UserResource', environment='prod'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Login APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='prod' , resource='UserResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Project APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=\"ProjectResource\" , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=\"ProjectResource\"}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Project APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"prod\", serviceName=\"ng-manager\" , resource='ProjectResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Org APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=\"OrganizationResource\" , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=\"OrganizationResource\"}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Org APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"prod\", serviceName=\"ng-manager\" , resource='OrganizationResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Connector APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'.*Connector.*' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'.*Connector.*'}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Connector APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"prod\",serviceName='ng-manager', resource=~'.*Connector.*' , method!~\"testGitRepoConnection\"}) # PL-51554 for more details on exclusion ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Secret APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'NGSecretManagerResource|NGSecretResourceV2' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'NGSecretManagerResource|NGSecretResourceV2'}[5m]))",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='prod', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='prod'}[5m])))\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Secret APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"prod\",serviceName='ng-manager', resource=~'NGSecretManagerResource|NGSecretResourceV2'})",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='prod'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Delegate APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'Delegate.*' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'Delegate.*'}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Delegate APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'Delegate.*'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Settings APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'SettingsResource|AccountSettingResource' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"prod\", serviceName=\"ng-manager\" , resource=~'SettingsResource|AccountSettingResource'}[5m]))",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'SettingResource|LoginSettingsResource|JiraSettingResource', environment='prod', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'SettingResource|LoginSettingsResource|JiraSettingResource', environment='prod'}[5m])))\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Settings APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"prod\",serviceName='ng-manager', resource=~'SettingsResource|AccountSettingResource'})",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (software_wings_resources_responses_count{serviceName='cg-manager' ,environment=\"prod\", resource=~'SettingResource|LoginSettingsResource|JiraSettingResource' , method!~\"listArtifactStreams|list\"}) # PL-51554 for more details on method exclusion",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Audits APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AuditResource', environment='prod', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AuditResource', environment='prod'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Audits APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='prod', resource='AuditResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Notification APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource', environment='prod', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource', environment='prod'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Notification APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource' , environment='prod'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "User Group ACL Permissioning Change Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (serviceName)(avg_over_time(access_control_user_group_operation_latency{serviceName='access-control' , namespace='harness-nextgen'}[5m]))",
       "legendFormat": "user group processing time"
      }
     ]
    },
    {
     "title": "Notification Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (job)(avg_over_time(notification_send_operation_latency{environment=\"prod\"}[5m]))",
       "legendFormat": "notifications latency"
      }
     ]
    }
   ]
  },
  { "title": "Prod-2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Account APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AccountResource', environment='free', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AccountResource', environment='free'}[5m])))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource='ServiceAccountResource', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource='ServiceAccountResource'}[5m])))\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Account APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='free', resource='AccountResource', method!~\"getAccountDetails\"}) # PL-51554for more details on exclusion of methods",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{serviceName='ng-manager', environment='free', resource='ServiceAccountResource'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Login APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'UserResource', environment='free', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='UserResource', environment='free'}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Login APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='free' , resource='UserResource'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Project APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=\"ProjectResource\" , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=\"ProjectResource\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Project APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"free\", serviceName=\"ng-manager\" , resource='ProjectResource'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Org APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=\"OrganizationResource\" , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=\"OrganizationResource\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Org APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"free\", serviceName=\"ng-manager\" , resource='OrganizationResource'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Connector APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=~'.*Connector.*' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=~'.*Connector.*'}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Connector APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"free\",serviceName='ng-manager', resource=~'.*Connector.*', method!~\"testGitRepoConnection\"}) # PL-51554 for more details on exclusion",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Secret APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=~'NGSecretManagerResource|NGSecretResourceV2' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=~'NGSecretManagerResource|NGSecretResourceV2'}[5m]))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='free', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='free'}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Secret APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"free\",serviceName='ng-manager', resource=~'NGSecretManagerResource|NGSecretResourceV2'})",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='free'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Delegate APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=~'Delegate.*' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=~'Delegate.*'}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Delegate APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"free\", serviceName=\"ng-manager\" , resource=~'Delegate.*'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Settings APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=~'SettingsResource|AccountSettingResource' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"free\", serviceName=\"ng-manager\" , resource=~'SettingsResource|AccountSettingResource'}[5m]))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'SettingResource|LoginSettingsResource|JiraSettingResource', environment='free', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'SettingResource|LoginSettingsResource|JiraSettingResource', environment='free'}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Settings APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"free\",serviceName='ng-manager', resource=~'SettingsResource|AccountSettingResource'})",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "avg by(method) (software_wings_resources_responses_count{serviceName='cg-manager' ,environment=\"free\", resource=~'SettingResource|LoginSettingsResource|JiraSettingResource' , method!~\"listArtifactStreams|list\"}) # PL-51554 for more details on method exclusion",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Audits APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AuditResource', environment='free', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AuditResource', environment='free'}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Audits APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='free', resource='AuditResource'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Notification APIs Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource', environment='free', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource', environment='free'}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Notification APIs P95 ART",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource' , environment='free'})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "User Group ACL Permissioning Change Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (serviceName)(avg_over_time(access_control_user_group_operation_latency{serviceName='access-control' , namespace='harness-nextgen-free'}[5m]))",
     "legendFormat": "user group processing time"
    }
   ]
  },
  {
   "title": "Notification Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (job)(avg_over_time(notification_send_operation_latency{environment=\"free\"}[5m]))",
     "legendFormat": "notifications latency"
    }
   ]
  },
  {
   "title": "Prod-3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AccountResource', environment='compliance', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AccountResource', environment='compliance'}[5m])))",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource='ServiceAccountResource', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource='ServiceAccountResource'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Account APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='compliance', resource='AccountResource', method!~\"getAccountDetails\"}) # PL-51554for more details on exclusion of methods",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{serviceName='ng-manager', environment='compliance', resource='ServiceAccountResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Login APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'UserResource', environment='compliance', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='UserResource', environment='compliance'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Login APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='compliance' , resource='UserResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Project APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=\"ProjectResource\" , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=\"ProjectResource\"}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Project APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"compliance\", serviceName=\"ng-manager\" , resource='ProjectResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Org APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=\"OrganizationResource\" , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=\"OrganizationResource\"}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Org APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"compliance\", serviceName=\"ng-manager\" , resource='OrganizationResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Connector APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'.*Connector.*' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'.*Connector.*'}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Connector APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"qa\",serviceName='ng-manager', resource=~'.*Connector.*', method!~\"testGitRepoConnection\"}) # PL-51554 for more details on exclusion",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Secret APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'NGSecretManagerResource|NGSecretResourceV2' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'NGSecretManagerResource|NGSecretResourceV2'}[5m]))",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='compliance', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='compliance'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Secret APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"compliance\",serviceName='ng-manager', resource=~'NGSecretManagerResource|NGSecretResourceV2'})",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='compliance'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Delegate APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'Delegate.*' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'Delegate.*'}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Delegate APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'Delegate.*'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Settings APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'SettingsResource|AccountSettingResource' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"compliance\", serviceName=\"ng-manager\" , resource=~'SettingsResource|AccountSettingResource'}[5m]))",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'SettingResource|LoginSettingsResource|JiraSettingResource', environment='compliance', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'SettingResource|LoginSettingsResource|JiraSettingResource', environment='compliance'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Settings APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"compliance\",serviceName='ng-manager', resource=~'SettingsResource|AccountSettingResource'})",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (software_wings_resources_responses_count{serviceName='cg-manager' ,environment=\"compliance\", resource=~'SettingResource|LoginSettingsResource|JiraSettingResource' , method!~\"listArtifactStreams|list\"}) # PL-51554 for more details on method exclusion",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Audits APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AuditResource', environment='compliance', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AuditResource', environment='compliance'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Audits APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='compliance', resource='AuditResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Notification APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource', environment='compliance', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource', environment='compliance'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Notification APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource' , environment='compliance'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "User Group ACL Permissioning Change Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (serviceName)(avg_over_time(access_control_user_group_operation_latency{serviceName='access-control' , namespace='harness-nextgen-compliance'}[5m]))",
       "legendFormat": "user group processing time"
      }
     ]
    },
    {
     "title": "Notification Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (job)(avg_over_time(notification_send_operation_latency{environment=\"compliance\"}[5m]))",
       "legendFormat": "notifications latency"
      }
     ]
    }
   ]
  },
  {
   "title": "QA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AccountResource', environment='qa', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AccountResource', environment='qa'}[5m])))",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource='ServiceAccountResource', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource='ServiceAccountResource'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Account APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='qa', resource='AccountResource', method!~\"getAccountDetails\"}) # PL-51554for more details on exclusion of methods",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{serviceName=\"ng-manager\",environment='qa', resource='ServiceAccountResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Login APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'UserResource', environment='qa', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='UserResource', environment='qa'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Login APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='qa', resource='UserResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Project APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=\"ProjectResource\" , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=\"ProjectResource\"}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Project APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"qa\", serviceName=\"ng-manager\" , resource='ProjectResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Org APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=\"OrganizationResource\" , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=\"OrganizationResource\"}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Org APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"qa\", serviceName=\"ng-manager\" , resource='OrganizationResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Connector APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'.*Connector.*' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'.*Connector.*'}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Connector APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"qa\",serviceName='ng-manager', resource=~'.*Connector.*', method!~\"testGitRepoConnection\"}) # PL-51554 for more details on exclusion",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Secret APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'NGSecretManagerResource|NGSecretResourceV2' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'NGSecretManagerResource|NGSecretResourceV2'}[5m]))",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='qa', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='qa'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Secret APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"qa\",serviceName='ng-manager', resource=~'NGSecretManagerResource|NGSecretResourceV2'})",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', resource=~'GcpSecretsManagerResource|GcpSecretsManagerResourceV2|AzureSecretsManagerResource|AwsSecretsManagerResource|CustomSecretsManagerResource', environment='qa'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Delegate APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'Delegate.*' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'Delegate.*'}[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Delegate APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'Delegate.*'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Settings APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'SettingsResource|AccountSettingResource' , statusCode=\"$status\"}[5m]))*100) \n/ \nsum by(method) \n(rate(io_harness_resources_responses_count{environment=\"qa\", serviceName=\"ng-manager\" , resource=~'SettingsResource|AccountSettingResource'}[5m]))",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'SettingResource|LoginSettingsResource|JiraSettingResource', environment='qa', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'SettingResource|LoginSettingsResource|JiraSettingResource', environment='qa'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Settings APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (io_harness_resources_responses_latency_snapshot_95thPercentile{environment=\"qa\",serviceName='ng-manager', resource=~'SettingsResource|AccountSettingResource'})",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "avg by(method) (software_wings_resources_responses_count{serviceName='cg-manager' ,environment=\"qa\", resource=~'SettingResource|LoginSettingsResource|JiraSettingResource' , method!~\"listArtifactStreams|list\"}) # PL-51554 for more details on method exclusion",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Audits APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AuditResource', environment='qa', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource='AuditResource', environment='qa'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Audits APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', environment='qa', resource='AuditResource'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Notification APIs Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource', environment='qa', statusCode='$status'}[5m]))*100) \n/ \n(sum by(method) \n(rate(software_wings_resources_responses_count{serviceName='cg-manager' ,resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource', environment='qa'}[5m])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Notification APIs P95 ART",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(method) (software_wings_resources_responses_latency_snapshot_95thPercentile{serviceName='cg-manager', resource=~'NotificationResource|NotificationSetupResource|AlertNotificationRuleResource' , environment='qa'})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "User Group ACL Permissioning Change Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (serviceName)(avg_over_time(access_control_user_group_operation_latency{serviceName='access-control' , namespace='harness-nextgen'}[5m]))",
       "legendFormat": "user group processing time"
      }
     ]
    },
    {
     "title": "Notification Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (job)(avg_over_time(notification_send_operation_latency{environment=\"qa\"}[5m]))",
       "legendFormat": "notifications latency"
      }
     ]
    }
   ]
  }
 ]
}