{
 "title": "Queue-Service - Overview",
 "tags": [
  "cd",
  "queue",
  "0compatible"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(enqueue_requests_per_module_success,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(enqueue_requests_per_module_success{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(enqueue_requests_per_module_success{cluster=\"$cluster\", namespace=\"$namespace\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Enqueue / Dequeue requests per module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(enqueue_requests_per_module_success{cluster=\"$cluster\", namespace=\"$namespace\", topic=~\".*${topic:pipe}\"}[5m]))",
     "legendFormat": "enqueue_requests_per_module_success"
    },
    {
     "expr": "sum(increase(dequeue_requests_per_module_success{cluster=\"$cluster\", namespace=\"$namespace\", topic=~\".*${topic:pipe}\"}[5m]))",
     "legendFormat": "dequeue_requests_per_module_success"
    },
    {
     "expr": "sum(increase(dequeue_requests_per_module_failure{cluster=\"$cluster\", namespace=\"$namespace\", topic=~\".*${topic:pipe}\"}[5m]))",
     "legendFormat": "dequeue_requests_per_module_failure"
    },
    {
     "expr": "sum(increase(enqueue_requests_per_module_failure{cluster=\"$cluster\", namespace=\"$namespace\", topic=~\".*${topic:pipe}\"}[5m]))",
     "legendFormat": "enqueue_requests_per_module_failure"
    }
   ]
  },
  { "title": "Ack / Queue / Dequeue requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/ack\", le=\"+Inf\", code=\"200\"}[5m])) by(url)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/queue\", le=\"+Inf\", code=\"200\"}[5m])) by(url)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/dequeue\", le=\"+Inf\", code=\"200\"}[5m])) by(url)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/ack\", le=\"+Inf\", code=\"400\" }[5m])) by(url)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/queue\", le=\"+Inf\", code!=\"200\"}[5m])) by(url)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/dequeue\", le=\"+Inf\", code=\"400\"}[5m])) by(url)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/ack\", code=\"200\"}[5m])) by (le, url))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/queue\", code=\"200\"}[5m])) by (le, url))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/dequeue\", code=\"200\"}[5m])) by (le, url))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/ack\", le=\"+Inf\", code=\"200\"}[5m])) by(url)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/queue\", le=\"+Inf\", code=\"200\"}[5m])) by(url)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(echo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", url=\"/v1/dequeue\", le=\"+Inf\", code=\"200\"}[5m])) by(url)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}